--COSTUM INSERTS

INSERT INTO CONSULTAS VALUES (6,to_date('20160110','YYYYMMDD'),9.00,4,4,90.00);
INSERT INTO consultas VALUES (7,to_date('20091003','YYYYMMDD'),16.00,3,3,75.00);
INSERT INTO consultas VALUES (8,to_date('20151003','YYYYMMDD'),17.00,4,4,75.00);
INSERT INTO consultas VALUES (9,to_date('20151003','YYYYMMDD'),18.00,1,3,75.00);
INSERT INTO consultas VALUES (10,to_date('20151004','YYYYMMDD'),13.00,1,4,75.00);

--EX A
SELECT nome_m, designacao 
FROM medicos, ESPECIALIDADE
WHERE medicos.esp_id = ESPECIALIDADE.ESP_ID;

--EX B
SELECT nome_d, morada FROM PACIENTES
where cp = (select cp from CPOSTAL 
                where localidade = 'Porto' );

--EX C
SELECT nome_m FROM MEDICOS, ESPECIALIDADE
WHERE ESPECIALIDADE.DESIGNACAO = 'Cardiologia'
AND ESPECIALIDADE.ESP_ID = MEDICOS.ESP_ID;

--EX D
SELECT nome_m FROM MEDICOS, ESPECIALIDADE
WHERE idade > 40 
AND ESPECIALIDADE.DESIGNACAO = 'Pediatria'
AND MEDICOS.ESP_ID = ESPECIALIDADE.ESP_ID;

--EX E 
SELECT nome_m FROM MEDICOS, ESPECIALIDADE, PACIENTES, CONSULTAS, CPOSTAL
WHERE MEDICOS.ESP_ID = ESPECIALIDADE.ESP_ID
AND MEDICOS.ID_MEDICO = CONSULTAS.ID_MEDICO
AND CONSULTAS.ID_PACIENTE = PACIENTES.ID_PACIENTE
AND PACIENTES.CP = CPOSTAL.CP
AND CPOSTAL.LOCALIDADE = 'Porto'
AND ESPECIALIDADE.DESIGNACAO = 'Pediatria';

--EX F
--O Group by pode ter um having que não é mostrado
SELECT NOME_m FROM MEDICOS, CONSULTAS
WHERE MEDICOS.ID_MEDICO = CONSULTAS.ID_MEDICO
AND MEDICOS.HOSPITAL LIKE 'S.João'
GROUP BY NOME_M
HAVING COUNT(CONSULTAS.ID_CONSULTA) < 10;

--EX G - 
SELECT DISTINCT NOME_m FROM MEDICOS, PACIENTES, CONSULTAS
WHERE MEDICOS.ID_MEDICO = CONSULTAS.ID_MEDICO
AND PACIENTES.ID_PACIENTE = CONSULTAS.ID_PACIENTE
AND MEDICOS.IDADE > 30
AND PACIENTES.IDADE < 20
AND CONSULTAS.HORA BETWEEN 12.0 AND 19.00;

--EX H
SELECT P.NOME_D FROM PACIENTES P
WHERE P.ID_PACIENTE NOT IN (
  SELECT C.ID_PACIENTE FROM CONSULTAS C, MEDICOS M, ESPECIALIDADE E
  WHERE E.ESP_ID = M.ESP_ID
  AND C.ID_MEDICO = M.ID_MEDICO
  AND E.DESIGNACAO = 'Pediatria')
AND P.IDADE > 10;

--EX I
SELECT DISTINCT E.DESIGNACAO FROM ESPECIALIDADE E, MEDICOS M, CONSULTAS C
WHERE M.ESP_ID = E.ESP_ID
AND M.ID_MEDICO = C.ID_MEDICO
AND C.DATA LIKE '15.09.%';

--EX J
SELECT M.NOME_M FROM MEDICOS M, ESPECIALIDADE E
WHERE M.ESP_ID = E.ESP_ID
AND E.DESIGNACAO = 'Cardiologia'
AND M.ID_MEDICO NOT IN (
  SELECT DISTINCT M.ID_MEDICO FROM ESPECIALIDADE E, MEDICOS M, CONSULTAS C
  WHERE M.ESP_ID = E.ESP_ID
  AND M.ID_MEDICO = C.ID_MEDICO
  AND C.DATA LIKE '15.09.%');
  
--EX K
SELECT P.NOME_D FROM PACIENTES P
WHERE P.IDADE < (SELECT MAX(P.IDADE) FROM PACIENTES P);

--EX L
SELECT DISTINCT P.NOME_D, P.MORADA FROM PACIENTES P, CONSULTAS C, MEDICOS M
WHERE P.ID_PACIENTE = C.ID_PACIENTE
AND M.ID_MEDICO = C.ID_MEDICO
AND M.HOSPITAL LIKE 'S.João';

--EX M - Try to do it without the exist
SELECT ID_PACIENTE, NOME_D  FROM PACIENTES P 
WHERE NOT EXISTS 
  (SELECT M.NOME_M FROM MEDICOS M 
  WHERE M.HOSPITAL LIKE 'S.João' 
  AND NOT EXISTS 
    (SELECT C.ID_MEDICO FROM CONSULTAS C
    WHERE M.ID_MEDICO = C.ID_MEDICO 
    AND C.ID_PACIENTE = P.ID_PACIENTE));
    
--EX N
--dosn't work
SELECT DISTINCT NOME_D FROM PACIENTES P, CONSULTAS C
WHERE P.ID_PACIENTE = C.ID_PACIENTE 
AND C.ID_CONSULTA NOT IN (
  SELECT ID_CONSULTA FROM CONSULTAS C, MEDICOS M, ESPECIALIDADE E
  WHERE M.ESP_ID = E.ESP_ID
  AND M.ID_MEDICO = C.ID_MEDICO
  AND E.DESIGNACAO <> 'Pediatria');
  
--works
SELECT DISTINCT P.nome_d 
FROM pacientes P, consultas C
WHERE C.id_paciente = P.id_paciente
AND P.id_paciente NOT IN 
  (SELECT id_paciente
   FROM   medicos M, especialidade E, consultas C
   WHERE  M.esp_id = E.esp_id
   AND M.id_medico = C.id_medico
   AND designacao <> 'Pediatria');

--works
SELECT DISTINCT P.nome_d 
FROM medicos M, especialidade E, pacientes P, consultas C
WHERE  M.esp_id = E.esp_id
AND C.id_medico = M.id_medico
AND C.id_paciente = P.id_paciente
AND P.id_paciente NOT IN 
  (SELECT id_paciente
   FROM   medicos M, especialidade E, consultas C
   WHERE  M.esp_id = E.esp_id
   AND M.id_medico = C.id_medico
   AND designacao <> 'Pediatria'); 

--EX O
SELECT NOME_M FROM MEDICOS
WHERE HOSPITAL LIKE 'S.João'
OR ID_MEDICO IN 
  (SELECT ID_MEDICO FROM CONSULTAS
  WHERE DATA < to_date('20100504','YYYYMMDD'));
  
--EX P
SELECT DISTINCT NOMEMED FROM MEDICAMENTOS MD, MEDICOS M, CONSULTAS C, RECEITAS R
WHERE R.MEDICAMENTO_ID = MD.MEDICAMENTO_ID
AND R.ID_CONSULTA = C.ID_CONSULTA
AND C.ID_MEDICO = M.ID_MEDICO
AND M.NOME_M LIKE 'João';

--EX Q
